{
    'name': 'Odoo 19 Accounting Financial Reports',
    'version': '1.0.2',
    'category': 'Invoicing Management',
    'description': 'Accounting Reports For Odoo 19, Accounting Financial Reports, '
                   'Odoo 19 Financial Reports',
    'summary': 'Accounting Reports For Odoo 19',
    'sequence': '1',
    'author': 'Odoo Mates, Odoo SA',
    'license': 'LGPL-3',
    'company': 'Odoo Mates',
    'maintainer': 'Odoo Mates',
    'support': 'odoomates@gmail.com',
    'website': 'https://www.youtube.com/watch?v=yA4NLwOLZms',
    'depends': ['account'],
    'live_test_url': 'https://www.youtube.com/watch?v=yA4NLwOLZms',
    "data": [
        "data/account_account_type.xml",
        "security/ir.model.access.csv",
        "views/account_account_type_views.xml",
        "views/financial_report.xml",
        "views/ledger_menu.xml",
        "views/menu.xml",
        "views/settings.xml",
        "report/report_aged_partner.xml",
        "report/report_financial.xml",
        "report/report_general_ledger.xml",
        "report/report_journal_audit.xml",
        "report/report_journal_entries.xml",
        "report/report_partner_ledger.xml",
        "report/report_tax.xml",
        "report/report_trial_balance.xml",
        "report/report.xml",
        "wizard/account_report_common_view.xml",
        "wizard/aged_partner.xml",
        "wizard/balance_sheet.xml",
        "wizard/general_ledger.xml",
        "wizard/journal_audit.xml",
        "wizard/partner_ledger.xml",
        "wizard/profit_and_loss.xml",
        "wizard/tax_report.xml",
        "wizard/trial_balance.xml"
    ],
    'pre_init_hook': '_pre_init_clean_m2m_models',
    'images': ['static/description/banner.gif'],
}
